"""Heartbeat and resume protocol helpers for Voqualizer.

A2.4 keeps the websocket heartbeat contract small and deterministic:
clients send ``voqualizer_ping`` with a client timestamp and the server replies
with ``voqualizer_pong`` containing the original timestamp, server time, and a
best-effort RTT estimate. Large negative/positive deltas are treated as clock
skew and reported as ``None`` rather than inventing a misleading RTT.
"""

from __future__ import annotations

from dataclasses import dataclass
from time import time
from typing import Any

DEFAULT_MAX_CLOCK_SKEW_MS = 60_000.0


@dataclass(frozen=True, slots=True)
class HeartbeatResult:
    """Computed heartbeat response fields."""

    ts: Any
    server_time: float
    rtt_ms: float | None

    def to_payload(self) -> dict[str, Any]:
        return {
            "event": "voqualizer_pong",
            "ts": self.ts,
            "server_time": self.server_time,
            "rtt_ms": self.rtt_ms,
        }


def server_time_ms() -> float:
    """Current wall-clock time in epoch milliseconds."""

    return time() * 1000.0


def compute_rtt_ms(
    client_ts: Any,
    server_now_ms: float | None = None,
    *,
    max_clock_skew_ms: float = DEFAULT_MAX_CLOCK_SKEW_MS,
) -> float | None:
    """Return a best-effort RTT estimate or ``None`` on invalid/skewed input.

    ``client_ts`` is expected to be an epoch-millisecond timestamp generated by
    the client. Because client/server clocks can differ, negative deltas or
    implausibly large deltas are reported as ``None``.
    """

    if not isinstance(client_ts, (int, float)):
        return None
    now = server_time_ms() if server_now_ms is None else float(server_now_ms)
    delta = now - float(client_ts)
    if 0 <= delta < float(max_clock_skew_ms):
        return round(delta, 3)
    return None


def build_pong(
    client_ts: Any,
    *,
    server_now_ms: float | None = None,
    max_clock_skew_ms: float = DEFAULT_MAX_CLOCK_SKEW_MS,
) -> HeartbeatResult:
    """Build a deterministic ``voqualizer_pong`` payload model."""

    now = server_time_ms() if server_now_ms is None else float(server_now_ms)
    return HeartbeatResult(
        ts=client_ts,
        server_time=now,
        rtt_ms=compute_rtt_ms(
            client_ts,
            now,
            max_clock_skew_ms=max_clock_skew_ms,
        ),
    )
